/* HYDR8 application controller. Sensor values are only shown when received from hardware. */
(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const config = window.HYDR8_CONFIG || {};
  const configured = Boolean(config.supabaseUrl?.startsWith('https://') && !config.supabaseUrl.includes('YOUR_') && config.supabaseAnonKey && !config.supabaseAnonKey.includes('YOUR_'));
  const supa = configured && window.supabase ? window.supabase.createClient(config.supabaseUrl, config.supabaseAnonKey) : null;
  const SESSION_KEY = 'hydr8.local.sessions.v2';
  const PROFILE_KEY = 'hydr8.local.profile.v2';
  const SERVICE_UUID = '19b10000-e8f2-537e-4f6c-d104768a1214';
  const CHARACTERISTIC_UUID = '19b10001-e8f2-537e-4f6c-d104768a1214';
  const BATTERY_SERVICE = 'battery_service';
  const BATTERY_LEVEL = 'battery_level';
  let user = null, profile = {}, sessions = [], period = 'week', active = null, timer = null, chart = null;
  let bleDevice = null, bleCharacteristic = null, batteryLevel = null, batteryUpdatedAt = null, charging = null;

  const readLocal = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); } catch { return fallback; } };
  const writeLocal = (key, value) => { try { localStorage.setItem(key, JSON.stringify(value)); return true; } catch { notice('This browser blocked local storage, so changes could not be saved.', 'error'); return false; } };
  function notice(message, type = 'info') { const node = $('appNotice'); if (!node) return; node.textContent = message; node.className = 'card mb-5 p-4 text-sm ' + (type === 'error' ? 'text-red-300 border-red-500/50' : type === 'ok' ? 'text-emerald-300 border-emerald-500/50' : 'text-slate-300'); node.classList.remove('hidden'); clearTimeout(node._timer); node._timer = setTimeout(() => node.classList.add('hidden'), 6000); }
  function toast(message) { const node = $('toast'); if (!node) return; node.innerHTML = '<div class="card px-4 py-3 text-sm shadow-xl" role="status">' + esc(message) + '</div>'; setTimeout(() => { node.textContent = ''; }, 4500); }
  function formatDuration(seconds) { const s = Math.max(0, Number(seconds) || 0); return [Math.floor(s / 3600), Math.floor(s % 3600 / 60), s % 60).map((n) => String(n).padStart(2, '0')).join(':'); }
  function scoreFor(session) { const intake = Number(session.fluid_intake_ml) || 0; const loss = session.sweat_rate_lph && session.duration_seconds ? Number(session.sweat_rate_lph) * Number(session.duration_seconds) / 3600 * 1000 : null; if (!intake && !loss) return null; const ratio = loss ? Math.min(1.2, intake / loss) : Math.min(1.2, intake / 500); return Math.round(Math.max(0, Math.min(100, 55 + ratio * 35 - (loss && intake < loss ? 10 : 0)))); }
  function periodStart() { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (period === 'week' ? 6 : period === 'month' ? 29 : 364)); return date; }
  function filteredSessions() { return sessions.filter((s) => new Date(s.started_at) >= periodStart()); }
  function setTab(tab) { document.querySelectorAll('.tab').forEach((node) => node.classList.toggle('active', node.id === tab)); document.querySelectorAll('.navbtn').forEach((node) => { const selected = node.dataset.tab === tab; node.classList.toggle('active', selected); node.setAttribute('aria-current', String(selected)); }); if (tab === 'history') renderHistory(); if (tab === 'insights') renderInsights(); }

  function updateAuthUi() { if ($('authBtn')) $('authBtn').textContent = user ? 'Settings' : 'Sign in'; }
  function fillProfile() { const values = { firstName: profile.first_name || '', email: user?.email || profile.email || '', favoriteGatoradeFlavor: profile.favorite_gatorade_flavor || 'Glacier Freeze', aiAssistantEnabled: profile.ai_assistant_enabled !== false, personalizationEnabled: profile.personalization_enabled !== false }; Object.entries(values).forEach(([id, value]) => { if ($(id)) $(id).type === 'checkbox' ? ($(id).checked = value) : ($(id).value = value); }); }
  function patchState() { return bleDevice ? 'connected' : 'disconnected'; }
  function renderPatch() {
    const connected = patchState() === 'connected';
    const battery = batteryLevel == null ? '—' : `${batteryLevel}%`;
    const last = batteryUpdatedAt ? new Date(batteryUpdatedAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : '—';
    if ($('bleStatus')) $('bleStatus').innerHTML = `<i class="dot ${connected ? 'ok' : 'muted'}"></i>${connected ? 'Connected' : 'Not connected'}`;
    if ($('patchConnectionCard')) $('patchConnectionCard').innerHTML = `<p class="text-sm font-semibold text-slate-200">HYDR8 PATCH</p><p class="mt-2 text-lg font-black">${connected ? '● Connected' : '○ Not connected'}</p><p class="muted text-xs mt-2">Battery: ${battery}</p><p class="muted text-xs mt-1">Last sync: ${last}</p><button id="connectPatchBtn" class="btn ${connected ? 'btn-ghost' : 'btn-primary'} w-full mt-3 py-2.5 text-sm">${connected ? 'Disconnect Patch' : 'Connect Patch'}</button>`;
    if ($('connectPatchBtn')) $('connectPatchBtn').onclick = connected ? disconnectPatch : connectPatch;
    if ($('patchBatteryCard')) $('patchBatteryCard').innerHTML = `<p class="muted text-xs uppercase tracking-[0.18em]">Patch Battery</p><div class="flex items-center justify-between mt-3"><div><div class="text-xl font-black">${batteryLevel == null ? '🔋 —' : `🔋 ${battery}`}</div><p class="muted text-xs mt-1">${batteryLevel == null ? 'Battery unavailable' : 'Live hardware reading'}</p></div><span class="battery-pill text-slate-300 bg-slate-800">${batteryLevel == null ? 'Unavailable' : batteryLevel >= 80 ? 'Full' : batteryLevel >= 50 ? 'Good' : batteryLevel >= 20 ? 'Low' : batteryLevel ? 'Very low' : 'Empty'}</span></div><p class="muted text-xs mt-3">${batteryLevel == null ? 'Connect your HYDR8 Patch to view battery level.' : `Last updated: ${last}`}</p>`;
    if ($('settingsPatchConnection')) $('settingsPatchConnection').textContent = connected ? 'Connected' : 'Not connected';
    if ($('settingsPatchBattery')) $('settingsPatchBattery').textContent = batteryLevel == null ? 'Battery unavailable' : `${battery} · Last updated: ${last}`;
    if ($('settingsPatchCharging')) $('settingsPatchCharging').textContent = charging == null ? 'Charging status unavailable.' : charging ? 'Charging' : 'Not charging';
    if ($('settingsDeviceInfo')) $('settingsDeviceInfo').textContent = connected ? `${bleDevice.name || 'HYDR8 Patch'} · Bluetooth connected` : 'No patch paired.';
  }
  function render() { updateAuthUi(); fillProfile(); renderPatch(); const list = filteredSessions().sort((a, b) => new Date(b.started_at) - new Date(a.started_at)); const latest = list[0]; const score = latest?.hydration_score ?? (latest ? scoreFor(latest) : null); if ($('score')) $('score').textContent = score ?? '—'; if ($('scoreLabel')) $('scoreLabel').textContent = score == null ? 'No estimate yet' : score >= 75 ? 'Good hydration estimate' : score >= 50 ? 'Moderate estimate' : 'Lower estimate'; if ($('fluid')) $('fluid').textContent = `${latest?.fluid_intake_ml || 0} ml`; if ($('sweat')) $('sweat').textContent = latest?.sweat_rate_lph ? `${Number(latest.sweat_rate_lph).toFixed(2)} L/hr` : 'Unavailable'; const flavor = profile.favorite_gatorade_flavor; if ($('aiAssistantText')) $('aiAssistantText').textContent = profile.ai_assistant_enabled === false ? 'AI assistance is disabled in Settings.' : `Keep monitoring your fluid intake and take regular drink breaks.${profile.personalization_enabled !== false && flavor && flavor !== 'I don’t drink Gatorade' ? ` Your hydration assistant knows you prefer ${flavor}.` : ''}`; renderHistory(); renderInsights(); }
  function renderHistory() { const node = $('historyList'); if (!node) return; if (!sessions.length) { node.innerHTML = '<div class="card p-6 text-center"><p class="text-lg font-bold">No workouts yet</p><p class="muted text-sm mt-1">Start your first workout to build history.</p></div>'; return; } node.innerHTML = sessions.slice().sort((a, b) => new Date(b.started_at) - new Date(a.started_at)).map((s) => `<article class="card p-4"><div class="flex justify-between gap-3"><div><h3 class="font-bold">${esc(s.sport || 'Workout')}</h3><p class="muted text-sm">${new Date(s.started_at).toLocaleString()}</p></div><strong>${formatDuration(s.duration_seconds)}</strong></div><p class="muted text-sm mt-2">Fluid: ${Number(s.fluid_intake_ml || 0)} ml · Estimate: ${s.hydration_score ?? scoreFor(s) ?? '—'}</p></article>`).join(''); }
  function renderInsights() { const list = filteredSessions(); if ($('statCount')) $('statCount').textContent = list.length; if ($('statScore')) $('statScore').textContent = list.length ? Math.round(list.reduce((sum, s) => sum + Number(s.hydration_score ?? scoreFor(s) ?? 0), 0) / list.length) : '—'; if (!window.Chart || !$('historyChart')) return; chart?.destroy(); chart = new Chart($('historyChart'), { type: 'line', data: { labels: list.slice().reverse().map((s) => new Date(s.started_at).toLocaleDateString()), datasets: [{ label: 'Estimate', data: list.slice().reverse().map((s) => scoreFor(s) ?? s.hydration_score ?? null), borderColor: '#3B82F6', backgroundColor: 'rgba(59,130,246,.2)', fill: true, tension: .3 }] }, options: { responsive: true, plugins: { legend: { display: false } }, scales: { y: { min: 0, max: 100 } } } }); }

  async function loadCloudData() { const [p, s] = await Promise.all([supa.from('profiles').select('*').eq('id', user.id).maybeSingle(), supa.from('sessions').select('*').eq('user_id', user.id).order('started_at', { ascending: false })]); profile = p.data || {}; sessions = s.data || []; }
  async function load() { if (supa) { const result = await supa.auth.getSession(); user = result.data.session?.user || null; if (user) await loadCloudData(); supa.auth.onAuthStateChange(async (_, session) => { user = session?.user || null; if (user) await loadCloudData(); else { profile = {}; sessions = []; } render(); }); } else { profile = readLocal(PROFILE_KEY, {}); sessions = readLocal(SESSION_KEY, []); } render(); }
  function openAuth() { $('modal')?.classList.remove('hidden'); $('authEmail')?.focus(); }
  function closeAuth() { $('modal')?.classList.add('hidden'); }
  async function submitAuth(event) { event.preventDefault(); if (!supa) return notice('Accounts are not configured yet. Guest mode saves data only in this browser.', 'info'); const email = $('authEmail').value.trim(); const password = $('authPassword').value; const flavor = $('authFavoriteFlavor').value; const result = $('authSubmit').textContent === 'Create account' ? await supa.auth.signUp({ email, password, options: { data: { favorite_gatorade_flavor: flavor } } }) : await supa.auth.signInWithPassword({ email, password }); if (result.error) return notice(result.error.message, 'error'); closeAuth(); toast('Authentication successful.'); }
  async function saveProfile(event) { event.preventDefault(); profile = { ...profile, first_name: $('firstName').value.trim(), email: $('email').value.trim(), favorite_gatorade_flavor: $('favoriteGatoradeFlavor').value, ai_assistant_enabled: $('aiAssistantEnabled').checked, personalization_enabled: $('personalizationEnabled').checked }; if (supa && user) { const { error } = await supa.from('profiles').upsert({ id: user.id, ...profile, hydration_preferences: { favorite_gatorade_flavor: profile.favorite_gatorade_flavor, ai_assistant_enabled: profile.ai_assistant_enabled, personalization_enabled: profile.personalization_enabled } }); if (error) return notice(error.message, 'error'); } else writeLocal(PROFILE_KEY, profile); render(); toast('Settings saved.'); }
  function openWorkout() { $('workoutModal')?.classList.remove('hidden'); $('wSport')?.focus(); }
  function startWorkout(event) { event.preventDefault(); active = { started: new Date(), sport: $('wSport').value.trim() || 'Workout', workout_type: $('wType').value, environment: $('wEnvironment').value, temperature: $('wTemp').value ? Number($('wTemp').value) : null, fluid_intake_ml: 0 }; $('workoutModal').classList.add('hidden'); timer = setInterval(() => { if ($('workoutDuration')) $('workoutDuration').textContent = formatDuration((Date.now() - active.started) / 1000); }, 1000); renderWorkout(); }
  function renderWorkout() { if ($('activeStatus')) $('activeStatus').textContent = active ? `${active.sport} · ${active.workout_type}` : 'No workout in progress'; if ($('workoutFluid')) $('workoutFluid').textContent = `${active?.fluid_intake_ml || 0} ml`; }
  function addFluid() { if (!active) return notice('Start a workout first.', 'info'); const amount = Number(window.prompt('How much fluid did you drink (ml)?')); if (Number.isFinite(amount) && amount > 0) { active.fluid_intake_ml += amount; renderWorkout(); } }
  async function endWorkout() { if (!active) return; clearInterval(timer); const ended = new Date(); const record = { user_id: user?.id, started_at: active.started.toISOString(), ended_at: ended.toISOString(), sport: active.sport, workout_type: active.workout_type, environment: active.environment, temperature: active.temperature, duration_seconds: Math.round((ended - active.started) / 1000), fluid_intake_ml: active.fluid_intake_ml, sweat_rate_lph: null, hydration_score: scoreFor({ ...active, duration_seconds: Math.round((ended - active.started) / 1000) }) }; if (supa && user) { const { error } = await supa.from('sessions').insert(record); if (error) return notice(error.message, 'error'); await loadCloudData(); } else { sessions.push(record); writeLocal(SESSION_KEY, sessions); } active = null; renderWorkout(); render(); toast('Workout saved.'); }
  function setBleStatus(state, message) { if ($('bleStatus')) $('bleStatus').innerHTML = `<i class="dot ${state === 'connected' ? 'ok' : state === 'connecting' ? 'warn' : 'muted'}"></i>${message}`; }
  async function connectPatch() { if (!navigator.bluetooth) return notice('Web Bluetooth isn’t supported by this browser. Use HTTPS in Chrome or Edge on a compatible device.', 'error'); try { setBleStatus('connecting', 'Connecting'); bleDevice = await navigator.bluetooth.requestDevice({ filters: [{ services: [SERVICE_UUID] }] }); bleDevice.addEventListener('gattserverdisconnected', disconnectPatch); const server = await bleDevice.gatt.connect(); const service = await server.getPrimaryService(SERVICE_UUID); bleCharacteristic = await service.getCharacteristic(CHARACTERISTIC_UUID); await bleCharacteristic.startNotifications(); bleCharacteristic.addEventListener('characteristicvaluechanged', handlePatchData); try { const batteryService = await server.getPrimaryService(BATTERY_SERVICE); const batteryCharacteristic = await batteryService.getCharacteristic(BATTERY_LEVEL); const readBattery = async () => { const value = await batteryCharacteristic.readValue(); batteryLevel = value.getUint8(0); batteryUpdatedAt = Date.now(); renderPatch(); }; await readBattery(); batteryCharacteristic.addEventListener('characteristicvaluechanged', (event) => { batteryLevel = event.target.value.getUint8(0); batteryUpdatedAt = Date.now(); renderPatch(); }); } catch { /* Battery service is optional; leave unavailable. */ } renderPatch(); notice('Patch connected. Waiting for hardware data.', 'ok'); } catch (error) { bleDevice = null; setBleStatus('disconnected', 'Not connected'); notice(error.name === 'NotFoundError' ? 'No patch was selected.' : `Patch connection failed: ${error.message}`, 'error'); } }
  function disconnectPatch() { if (bleDevice?.gatt?.connected) bleDevice.gatt.disconnect(); bleDevice = null; bleCharacteristic = null; batteryLevel = null; batteryUpdatedAt = null; charging = null; renderPatch(); toast('Patch disconnected.'); }
  function handlePatchData(event) { const raw = new TextDecoder().decode(event.target.value).trim(); let parsed; try { parsed = JSON.parse(raw); } catch { return notice('Received unsupported patch data. No sensor estimate was created.', 'error'); } if (typeof parsed.battery === 'number' && parsed.battery >= 0 && parsed.battery <= 100) { batteryLevel = parsed.battery; batteryUpdatedAt = Date.now(); } if (typeof parsed.charging === 'boolean') charging = parsed.charging; renderPatch(); }
  function exportData() { const blob = new Blob([JSON.stringify({ profile, sessions }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'hydr8-data.json'; link.click(); URL.revokeObjectURL(link.href); }

  document.addEventListener('DOMContentLoaded', () => { document.querySelectorAll('.navbtn').forEach((button) => button.addEventListener('click', () => setTab(button.dataset.tab))); document.querySelectorAll('.period').forEach((button) => button.addEventListener('click', () => { period = button.dataset.period; renderInsights(); })); $('authBtn')?.addEventListener('click', () => user ? setTab('settings') : openAuth()); $('closeAuthModal')?.addEventListener('click', closeAuth); $('modal')?.addEventListener('click', (event) => { if (event.target === $('modal')) closeAuth(); }); $('authForm')?.addEventListener('submit', submitAuth); $('authToggle')?.addEventListener('click', () => { const create = $('authSubmit').textContent !== 'Create account'; $('authSubmit').textContent = create ? 'Create account' : 'Sign in'; $('modalTitle').textContent = create ? 'Create account' : 'Sign in'; }); $('profileForm')?.addEventListener('submit', saveProfile); $('startWorkoutBtn')?.addEventListener('click', openWorkout); $('workoutForm')?.addEventListener('submit', startWorkout); $('addFluidBtn')?.addEventListener('click', addFluid); $('endWorkoutBtn')?.addEventListener('click', endWorkout); $('connectPatchBtn')?.addEventListener('click', connectPatch); $('shopBtn')?.addEventListener('click', () => notice('Patch ordering is coming soon. No payment was requested or collected.', 'info')); ['upgradeBtn', 'manageSubBtn', 'cancelSubBtn'].forEach((id) => $(id)?.addEventListener('click', () => notice('Subscription management is coming soon. A payment provider has not been connected.', 'info'))); $('exportDataBtn')?.addEventListener('click', exportData); $('clearBtn')?.addEventListener('click', () => { if (confirm('Delete local workout history?')) { sessions = []; writeLocal(SESSION_KEY, sessions); render(); } }); $('clearLocalBtn')?.addEventListener('click', () => { if (confirm('Clear local HYDR8 data?')) { localStorage.removeItem(SESSION_KEY); localStorage.removeItem(PROFILE_KEY); profile = {}; sessions = []; render(); toast('Local data cleared.'); } }); $('scoreHelp')?.addEventListener('click', () => notice('This is an informational estimate based on logged workout and fluid data. It is not medical advice.', 'info')); load(); });
})();
