/* HYDR8 application controller: keeps data honest, supports Supabase when configured and a clearly local-only guest mode. */
(() => {
'use strict';
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const configured=window.HYDR8_CONFIG?.supabaseUrl?.startsWith('https://')&&!window.HYDR8_CONFIG.supabaseUrl.includes('YOUR_')&&window.HYDR8_CONFIG.supabaseAnonKey&&!window.HYDR8_CONFIG.supabaseAnonKey.includes('YOUR_');
const supa=configured&&window.supabase?window.supabase.createClient(HYDR8_CONFIG.supabaseUrl,HYDR8_CONFIG.supabaseAnonKey):null;
let user=null,profile={},sessions=[],period='week',active=null,timer=null,chart=null,bleDevice=null,bleChar=null,authMode='signin';
const STORE='hydr8.local.sessions.v2',PROFILE='hydr8.local.profile.v2'; const SERVICE='19b10000-e8f2-537e-4f6c-d104768a1214',CHAR='19b10001-e8f2-537e-4f6c-d104768a1214';
function notice(msg,type='info'){const n=$('appNotice');n.textContent=msg;n.className='card mb-5 p-4 text-sm '+(type==='error'?'text-red-300 border-red-500/50':type==='ok'?'text-emerald-300 border-emerald-500/50':'text-slate-300');n.classList.remove('hidden');setTimeout(()=>n.classList.add('hidden'),5000)}
function toast(msg){$('toast').innerHTML='<div class="card px-4 py-3 text-sm shadow-xl">'+esc(msg)+'</div>';setTimeout(()=>{$('toast').innerHTML=''},3500)}
function localSessions(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}} function saveLocal(){localStorage.setItem(STORE,JSON.stringify(sessions))}
function formatDuration(s){s=Math.max(0,Number(s)||0);return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(n=>String(n).padStart(2,'0')).join(':')}
function scoreFor(s){const intake=Number(s.fluid_intake_ml)||0,loss=s.sweat_rate_lph&&s.duration_seconds?Number(s.sweat_rate_lph)*Number(s.duration_seconds)/3600*1000:null;if(!intake&&!loss)return null;const ratio=loss?Math.min(1.2,intake/loss):Math.min(1.2,intake/500);return Math.round(Math.max(0,Math.min(100,55+ratio*35-(loss&&intake<loss?10:0))))}
function startOfPeriod(){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(period==='week'?6:period==='month'?29:364));return d} function filtered(){return sessions.filter(s=>new Date(s.started_at)>=startOfPeriod())}
function setTab(tab){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===tab));document.querySelectorAll('.navbtn').forEach(x=>x.setAttribute('aria-current',String(x.dataset.tab===tab)));if(tab==='history')renderHistory();if(tab==='insights')renderInsights()}
function updateAuth(){ $('authLabel').textContent=user?(profile.first_name||user.email):'Guest mode';$('authBtn').textContent=user?'Profile':'Sign in';$('signOut').classList.toggle('hidden',!user);$('greeting').textContent=user?'Welcome, '+(profile.first_name||'athlete'):'Welcome to HYDR8'}
function fillProfile(){['first_name','age_range','sport','units'].forEach(k=>{const id={first_name:'firstName',age_range:'ageRange',sport:'sport',units:'units'}[k];$(id).value=profile[k]||''});$('notifications').checked=profile.notification_preferences?.enabled!==false}
function render(){updateAuth();const f=filtered(),last=f[0],score=last?.hydration_score??(last?scoreFor(last):null);$('score').textContent=score??'—';$('scoreLabel').textContent=score===null?'No estimate yet':score>=75?'Good hydration estimate':score>=50?'Moderate estimate':'Lower estimate';$('fluid').textContent=(last?.fluid_intake_ml||0)+' ml';$('sweat').textContent=last?.sweat_rate_lph?Number(last.sweat_rate_lph).toFixed(2)+' L/hr':'Unavailable';$('temp').textContent=last?.temperature==null?'Unavailable':last.temperature+'°'+(profile.units||'F');$('patch').textContent=bleDevice?'Connected':'Not connected';const today=f.filter(s=>new Date(s.started_at).toDateString()===new Date().toDateString());$('todaySummary').textContent=today.length?today.length+' workout'+(today.length===1?'':'s')+' recorded today.':'No workout recorded today.';renderHistory();renderInsights()}
function renderHistory(){const list=$('historyList');if(!sessions.length){list.innerHTML='<div class="card p-6 text-center"><p class="text-lg font-bold">No workouts yet</p><p class="muted text-sm mt-1">Start your first workout to begin building your hydration history.</p></div>';return}list.innerHTML=sessions.slice().sort((a,b)=>new Date(b.started_at)-new Date(a.started_at)).map(s=>'<article class="card p-4"><div class="flex justify-between gap-3"><div><h3 class="font-bold">'+esc(s.sport)+' · '+esc(s.workout_type)+'</h3><p class="muted text-xs mt-1">'+new Date(s.started_at).toLocaleString()+' · '+formatDuration(s.duration_seconds)+'</p><p class="muted text-xs mt-2">'+esc(s.environment||'Condition not recorded')+' · '+Number(s.fluid_intake_ml||0)+' ml · '+(s.sweat_rate_lph?Number(s.sweat_rate_lph).toFixed(2)+' L/hr sweat estimate':'sweat unavailable')+'</p></div><strong class="text-blue-300">'+(s.hydration_score??scoreFor(s)??'—')+'</strong></div></article>').join('')}
function renderInsights(){const f=filtered(),avg=k=>f.length?f.reduce((a,s)=>a+Number(s[k]||0),0)/f.length:0;$('statCount').textContent=f.length;$('statScore').textContent=f.length?Math.round(f.reduce((a,s)=>a+Number(s.hydration_score??scoreFor(s)??0),0)/f.length):'—';$('statFluid').textContent=Math.round(avg('fluid_intake_ml'))+' ml';$('statDuration').textContent=formatDuration(Math.round(avg('duration_seconds')));$('insightText').textContent=f.length?`${f.length} workout${f.length===1?'':'s'} in this period. Average fluid intake was ${Math.round(avg('fluid_intake_ml'))} ml.`:'Not enough data yet. Complete more workouts to generate personalized insights.';chart?.destroy();const labels=f.slice().reverse().map(s=>new Date(s.started_at).toLocaleDateString()),data=f.slice().reverse().map(s=>s.hydration_score??scoreFor(s));chart=new Chart($('historyChart'),{type:'line',data:{labels,datasets:[{label:'Estimate',data,borderColor:'#3B82F6',backgroundColor:'rgba(59,130,246,.2)',fill:true,tension:.3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100}}}})}
async function load(){if(supa){const r=await supa.auth.getSession();user=r.data.session?.user||null;if(user){const [p,h]=await Promise.all([supa.from('profiles').select('*').eq('id',user.id).maybeSingle(),supa.from('sessions').select('*').eq('user_id',user.id).order('started_at',{ascending:false})]);profile=p.data||{};sessions=h.data||[];fillProfile()}supa.auth.onAuthStateChange(async(_,session)=>{user=session?.user||null;if(user){await load()}else{sessions=[];profile={};render()}})}else{sessions=localSessions();try{profile=JSON.parse(localStorage.getItem(PROFILE)||'{}')}catch{profile={}}fillProfile()}render()}
function openAuth(){ $('modal').classList.remove('hidden');$('email').focus()} function closeAuth(){$('modal').classList.add('hidden')}async function auth(e){e.preventDefault();if(!supa)return notice('Account features are not configured yet. Add Supabase URL and anon key in supabase-config.js.','error');$('authSubmit').disabled=true;try{const email=$('email').value.trim(),password=$('password').value;const r=authMode==='signin'?await supa.auth.signInWithPassword({email,password}):await supa.auth.signUp({email,password,options:{data:{first_name:$('authName').value.trim()}}});if(r.error)throw r.error;if(!r.data.session)notice('Check your email to confirm your account.','ok');else toast('Signed in successfully.');closeAuth()}catch(e){notice('We could not sign you in. Check your email and password.','error')}finally{$('authSubmit').disabled=false}}
async function saveProfile(e){e.preventDefault();const p={first_name:$('firstName').value.trim(),age_range:$('ageRange').value,sport:$('sport').value.trim(),units:$('units').value,notification_preferences:{enabled:$('notifications').checked}};if(supa&&user){const r=await supa.from('profiles').upsert({id:user.id,...p,updated_at:new Date().toISOString()});if(r.error)return notice('Settings could not be saved. Please try again.','error')}profile=p;if(!supa)localStorage.setItem(PROFILE,JSON.stringify(p));render();toast('Settings saved.')}
function openWorkout(){if(!user&&supa)return openAuth();$('workoutModal').classList.remove('hidden');$('wSport').focus()}function startWorkout(e){e.preventDefault();active={started:new Date(),sport:$('wSport').value.trim(),workout_type:$('wType').value,environment:$('wEnvironment').value,temperature:$('wTemp').value?Number($('wTemp').value):null,fluid:0,sweat:null,sensor_data:{}};$('workoutModal').classList.add('hidden');setTab('workout');const started=Date.now();timer=setInterval(()=>{$('timer').textContent=formatDuration(Math.floor((Date.now()-started)/1000))},1000);toast('Workout started.')}
function addFluid(){if(!active)return;const amount=Number(prompt('How much fluid did you drink (ml)?'));if(!Number.isFinite(amount)||amount<=0)return notice('Enter a positive amount in millilitres.','error');active.fluid+=amount;$('liveFluid').textContent=active.fluid+' ml';toast('Fluid intake recorded.')}
async function endWorkout(){if(!active)return;clearInterval(timer);const ended=new Date(),record={user_id:user?.id,started_at:active.started.toISOString(),ended_at:ended.toISOString(),sport:active.sport,workout_type:active.workout_type,environment:active.environment,temperature:active.temperature,duration_seconds:Math.round((ended-active.started)/1000),fluid_intake_ml:active.fluid,sweat_rate_lph:active.sweat,hydration_score:null,sensor_data:active.sensor_data,warnings:[]};record.hydration_score=scoreFor(record);try{if(supa&&user){const r=await supa.from('sessions').insert(record);if(r.error)throw r.error;await load()}else{delete record.user_id;sessions.push(record);saveLocal();render()}active=null;setTab('history');toast('Workout saved.')}catch{notice('Your workout could not be saved. Please try again.','error')}}
async function signOut(){if(supa)await supa.auth.signOut();else{user=null;sessions=localSessions()}render();toast('Signed out.')}
async function connect(){if(!navigator.bluetooth)return notice('Bluetooth is unavailable here. Use HTTPS in Chrome or Edge on a supported device.','error');$('bleStatus').innerHTML='<i class="dot warn"></i>CONNECTING';try{bleDevice=await navigator.bluetooth.requestDevice({filters:[{name:'HYDR8_Patch'}],optionalServices:[SERVICE]});bleDevice.addEventListener('gattserverdisconnected',disconnect);const server=await bleDevice.gatt.connect(),service=await server.getPrimaryService(SERVICE);bleChar=await service.getCharacteristic(CHAR);await bleChar.startNotifications();bleChar.addEventListener('characteristicvaluechanged',bleData);$('bleStatus').innerHTML='<i class="dot ok"></i>CONNECTED · waiting for patch data';render();toast('Patch connected.')}catch(e){bleDevice=null;$('bleStatus').innerHTML='<i class="dot"></i>NOT CONNECTED';notice('Unable to connect to HYDR8 Patch. Make sure it is powered on and nearby.','error')}}function disconnect(){bleDevice=null;bleChar=null;$('bleStatus').innerHTML='<i class="dot"></i>NOT CONNECTED';render();toast('Patch disconnected.')}
function bleData(e){const parts=new TextDecoder().decode(e.target.value).split(',');const temp=Number(parts[0]),raw=Number(parts[1]);if(!Number.isFinite(temp)||!Number.isFinite(raw))return;const sweat=(raw/1023)*2;if(active){active.sweat=sweat;active.sensor_data={source:'ble',temperature:temp,sweat_raw:raw}}$('liveSweat').textContent=sweat.toFixed(2)+' L/hr';$('temp').textContent=temp+'°'+(profile.units||'F')}
$('authBtn').onclick=()=>user?setTab('settings'):openAuth();$('viewBtn').onclick=()=>notice('The responsive dashboard is optimized for this layout.','info');$('scoreHelp').onclick=()=>notice('The estimate combines recorded fluid intake with workout duration and sweat-rate data when available. Temperature and patch readings may add context. It is a transparent prototype estimate, not a medically validated measurement.','info');document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('startBtn').onclick=openWorkout;$('endBtn').onclick=endWorkout;$('addFluid').onclick=addFluid;$('bleBtn').onclick=connect;$('signOut').onclick=signOut;$('profileForm').onsubmit=saveProfile;$('workoutForm').onsubmit=startWorkout;$('authForm').onsubmit=auth;$('modalClose').onclick=closeAuth;document.querySelectorAll('.period').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('.period').forEach(x=>x.classList.toggle('bg-blue-600',x===b));renderInsights()});$('authToggle').onclick=()=>{authMode=authMode==='signin'?'signup':'signin';$('modalTitle').textContent=authMode==='signin'?'Sign in':'Create account';$('authSubmit').textContent=authMode==='signin'?'Sign in':'Create account';$('nameWrap').classList.toggle('hidden',authMode==='signin')};$('resetBtn').onclick=async()=>{if(!supa)return notice('Configure Supabase before requesting a password reset.','error');const email=$('email').value.trim();if(!email)return notice('Enter your email first.','error');const r=await supa.auth.resetPasswordForEmail(email,{redirectTo:location.href});notice(r.error?'Password reset could not be requested.':'Password reset email requested.','ok')};$('clearBtn').onclick=()=>{if(supa&&user)return notice('Cloud history is managed by your account and is not cleared from this device.','info');if(confirm('Delete all locally saved HYDR8 workout history? This cannot be undone.')){sessions=[];saveLocal();render();toast('Local history cleared.')}};load();
})();
